using Spectre.Console;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace OOP_Main {
    public class ProductScreen: BaseScreen {
        public ProductScreen(Data appData): base(appData) { }

        public override string Show() => ShowListScreen("Products", _appData.Products);

        public void AddingProduct(Product newProduct, string supplierChoice) {
            _appData.AddProduct(newProduct);
            _appData.GetSupplierByName(supplierChoice).AddProductToCatalog(newProduct);
            AnsiConsole.MarkupLine($"[green bold]New product is created! You can check it on \"{GetEnumDescription(MenuOption.ShowProducts)}\" screen.[/]");
        }

        public override string Create() {
            AnsiConsole.Clear();
            ShowHeader("[bold]Adding product[/]");

            if (Tools.ValidateArray(_appData.Suppliers)) {
                AnsiConsole.MarkupLine("[red bold]No suppliers found. Call the admin to fix this issue[/]");
                return BackToMenuPrompt();
            }

            var factories = new Dictionary<string, ProductFactory> {
                { "Electronic product", new ElectronicProductFactory() },
                { "Cloth", new ClothFactory() },
                { "Furniture", new FurnitureFactory() },
                { "Sofa", new FurnitureFactory() },
            };       

            var prompt = new SelectionPrompt<string>()
                .Title("Select product [green]category[/]")
                .PageSize(15)
                .AddChoiceGroup("Electronic product", new[]
                {
                    "Electronic product"
                })
                .AddChoiceGroup("Cloth", new[]
                {
                    "Cloth"
                })
                .AddChoiceGroup("Furniture", new[]
                {
                    "Sofa", "Other furniture"
                });
            var categoryChoice = AnsiConsole.Prompt(prompt);

            Type productType = typeof(Product);
            switch (categoryChoice) {
                case "Electronic product": productType = typeof(ElectronicProduct); break;
                case "Cloth": productType = typeof(Cloth); break;
                case "Sofa": productType = typeof(Sofa); break;
                case "Other furniture": productType = typeof(Furniture); break;
            }

            string autoGeneratedArticle = _appData.GenerateNextProductArticle(productType);

            AnsiConsole.Clear();
            ShowHeader("[bold]Adding product[/]");

            string nameChoice = DefaultTextPrompt<string>("Enter product [green]name[/]:");

            double priceChoice = DefaultTextPrompt<double>("Enter product [green]price (in dollars)[/]:");

            List<string> suppliers = new List<string>();
            foreach (var supplier in _appData.Suppliers) {
                suppliers.Add(supplier.Name);
            }
            var supplierPrompt = new SelectionPrompt<string>()
                .Title("Select product [green]supplier[/]")
                .PageSize(15)
                .AddChoices(suppliers);

            string supplierChoice = AnsiConsole.Prompt(supplierPrompt);

            int supplierId = _appData.GetSupplierByName(supplierChoice).SupplierId;

            switch (categoryChoice) {
                case "Electronic product":
                    Product newElectronicProduct = factories["Electronic product"].CreateProduct(autoGeneratedArticle, nameChoice, priceChoice, supplierId);

                    AddingProduct(newElectronicProduct, supplierChoice);
                    break;

                case "Cloth":
                    Product newCloth = factories["Cloth"].CreateProduct(autoGeneratedArticle, nameChoice, priceChoice, supplierId);

                    AddingProduct(newCloth, supplierChoice);
                    break;

                case "Sofa":
                case "Other furniture":
                    if (categoryChoice == "Sofa") {
                        Product newSofa = factories["Sofa"].CreateProduct(autoGeneratedArticle, nameChoice, priceChoice, supplierId, "Sofa");

                        AddingProduct(newSofa, supplierChoice);
                    }
                    else {
                        Product newFurniture = factories["Other furniture"].CreateProduct(autoGeneratedArticle, nameChoice, priceChoice, supplierId);

                        AddingProduct(newFurniture, supplierChoice);
                    }
                    break;
                default:
                    AnsiConsole.MarkupLine("[red]Factory for this category is not implemented yet.[/]");
                    break;
            }

            return BackToMenuPrompt();
        }

        public override string Delete() {
            AnsiConsole.Clear();
            ShowHeader("[bold]Delete product[/]");

            if (Tools.ValidateArray(_appData.Products)) {
                AnsiConsole.MarkupLine("[red bold]There are no products to delete.[/]");
                return BackToMenuPrompt();
            }

            var choices = new List<string>();
            foreach (var p in _appData.Products) {
                choices.Add($"({p.Article}) {p.Name} - {p.Price}$");
            }
            choices.Add("Cancel");

            var selectedChoice = AnsiConsole.Prompt(
                new SelectionPrompt<string>()
                    .Title("Select a product to delete:")
                    .PageSize(10)
                    .AddChoices(choices));

            if (selectedChoice == "Cancel") return BackToMenuPrompt();

            string article = selectedChoice.Split(')')[0].TrimStart('(');
            Product productToDelete = _appData.Products.FirstOrDefault(p => p.Article == article);

            if (productToDelete != null) {
                bool confirm = AnsiConsole.Confirm(
                    $"Are you sure you want to delete [red]\"{productToDelete.Name}\"[/] ({productToDelete.Article})?",
                    defaultValue: false
                );

                if (confirm) {
                    bool isDeleted = _appData.DeleteProductByArticle(productToDelete.Article);
                    if (isDeleted) {
                        AnsiConsole.MarkupLine("[green]Product successfully deleted![/]");
                    }
                    else {
                        AnsiConsole.MarkupLine("[red]Failed to delete product.[/]");
                    }
                }
                else {
                    AnsiConsole.MarkupLine("[yellow]Deleting cancelled.[/]");
                }
            }

            return BackToMenuPrompt();
        }

        public string Edit() {
            AnsiConsole.Clear();
            ShowHeader("[bold]Edit Product[/]");

            var productChoice = AnsiConsole.Prompt(
                new SelectionPrompt<Product>()
                    .Title("Select product to edit:")
                    .UseConverter(p => $"{p.Name} ({p.Price}$)")
                    .AddChoices(_appData.Products));

            List<string> fieldNames = productChoice.GetType().GetProperties().Select(f => f.Name).ToList();
            var fieldChoice = AnsiConsole.Prompt(
                new SelectionPrompt<string>()
                    .Title("Select field to edit:")
                    .AddChoices(fieldNames));

            if (fieldChoice == "Price") {
                double newPrice = DefaultTextPrompt<double>($"Enter new price for {productChoice.Name}:");
                productChoice.Price = newPrice;
                _appData.ChangeProductPriceByArticle(productChoice.Article, newPrice);
                AnsiConsole.MarkupLine("[green]Product updated successfully![/]");
            }

            return BackToMenuPrompt();
        }
    }
}
